### PR TITLE
README.md: add getting started guide

### PR DESCRIPTION
**Pull request by omnidan**
closes https://github.com/gloomyson/StarCraft/issues/11

### CODE REVIEW

**Comment by phillipPhillip** [comment]
http://cdn.rawgit.com/gloomyson/StarCraft/master/index.html works online for slow computers... THE AI SEEMS TO BE TOO SMART ON SOME OF THE LEVELS

**Comment by phillipPhillip** [comment]
other teams units make confirmation sounds...?

**Comment by phillipPhillip** [comment]
dont waste time utilize this
http://cdn.rawgit.com/gloomyson/StarCraft/master/index.html

**Comment by xboi209** [comment]
@phillipPhillip Please only write about things concerning this issue

**Comment by phillipPhillip** [comment]
cool see new issues updated #up #closed

**Pull request merged**
