### PR TITLE
Two zergs for 50 minerals

### LINKED ISSUE #5: Two zerglings cost 25 minerals

### PR DESCRIPTION
**Pull request by konstruktoid**
See http://wiki.teamliquid.net/starcraft/Zergling and http://starcraft.wikia.com/wiki/Zergling_(StarCraft).
You get two zerglings for 50 minerals, but they count as 1 unit.
Closes #5 
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

### CODE REVIEW

**Comment by gloomyson** [comment]
Thanks for playing so carefully, I forgot this one, scourage must have the same issue, I see your pull request but I set that cost means one unit cost, should not change to 50, I can make tooltip to show cost by *(chara.birthCount?)chara.birthCount

**Comment by gloomyson** [comment]
Thanks for playing so carefully, I forgot this one, scourage must have the same issue, I see your pull request but that cost means one unit cost, should not change to 50, I can make tooltip to show cost by *(chara.birthCount?chara.birthCount:1), will check in with next revision.

**Comment by gloomyson** [comment]
The position for show cost in tooltip is at line #365 in button.js

**Comment by gloomyson** [comment]
Fix your issue in 8431b9b

**Comment by konstruktoid** [comment]
Thanks for the fix @gloomyson, and sorry for the delay.

**Pull request closed without merging**
